# 5.5.2. Exercise 2: NumPy Array Calculator Implementation

Design a calculator system for handling NumPy array operations by implementing a set of functions. The calculator should support operations between bidimensional arrays, including:

 - Addition
 - Subtraction
 - Multiplication (Matrix multiplication)
 - Concatenation
 - Transpose

Your task is to implement the following functions:
A main calculator function that receives two NumPy arrays and an operation string as parameters
Helper functions for each specific operation

## 5.5.2.1. Requirements:

The main calculator function should have the following signature:

In [ ]:
#NO EJECUTAR
def array_calculator(array1: np.ndarray, array2: np.ndarray, operation: str) -> np.ndarray:
    """
    Performs the specified operation between two NumPy arrays.
    
    Parameters:
    array1 (np.ndarray): First input array
    array2 (np.ndarray): Second input array
    operation (str): Operation to perform ('+', '-', '*', 'concat', 'transpose')
    
    Returns:
    np.ndarray: Result of the operation
    """

The function should handle the following cases:
- Valid operations between compatible arrays
- Error handling for incompatible array dimensions
- Error handling for unsupported operations
- Never use input(), since it was used last year Example:

In [ ]:
#NO EJECUTAR
import numpy as np
# Example arrays
a = np.array([[0, 1, 2], 
            [3, 4, 5], 
            [6, 7, 8]])

b = np.array([[0, 1, 2], 
            [3, 4, 5], 
            [6, 7, 8]])

# Addition example
result = array_calculator(a, b, '+')
# Expected output:
# array([[ 0,  2,  4],
#        [ 6,  8, 10],
#        [12, 14, 16]])

# Invalid operation example
result = array_calculator(a, b, '&')
# Should raise ValueError with message: "Operation '&' not supported"

## 5.5.2.2. Hints:

1. Use NumPy’s built-in functions for array operations

2. Implement error checking for:

- Array dimension compatibility

- Valid operation types

- Array shape requirements for specific operations

## ------------------------------------------------------------

## Reporte del Ejercicio 2: Calculadora NumPy
Para este ejercicio, he diseñado una calculadora que trabaja con dos matrices y realiza operaciones entre ellas.

### ¿Qué operaciones puede hacer?
La calculadora tiene cinco operaciones:

- Suma (+) y Resta (-): Operaciones elemento a elemento que necesitan que tengan el mismo tamaño.

- Multiplicación (*): He metido la multiplicación matricial (@) revisando antes que las columnas del primero coincidan con las filas del segundo

- Concatenación (concat): Une las matrices verticalmente (hacia abajo), por lo que controlo que tengan el mismo número de columnas (Amplío la cantidad de filas).

- Transpuesta (transpose): Devuelve la matriz A, traspuesta (filas por columnas, no debemos revisar nada).

### ¿Qué partes se pueden modificar?
Dentro de la función main(), he dejado una sección donde se pueden cambiar los valores de las matrices a y b, además de la variable "signo". Simplemente cambias el string de signo por uno de la lista comentada (['+', '-', '*', 'concat', 'transpose']) y el programa ejecutará la operación que toque.

### Fallos resueltos:
En cuanto al manejo de errores. He abordado los fallos de dimensiones (como intentar sumar matrices de distinto tamaño) y fallos de compatibilidad en la multiplicación (en cuanto a filas y columnas).


Además, el código lanza un ValueError si se introduce un signo o una letra que no está en la lista de operaciones (por ejemplo, una 'M' o un '&').
El ejercicio me pide que indique con una sola linea, el error al introducir un símbolo que no forme parte de los signos de la lista de operaciones, pero Python genera un Traceback completo. Esto puede dar la sensación visual de que hay "dos errores", pero en realidad es un solo fallo; lo que ocurre es que Python nos muestra la ruta desde donde se llamó la función (main) hasta la línea exacta donde saltó el error (raise).

NOTA: Tras una búsqueda, me he dado cuenta de que necesitaría usar Try y Except para solucionar el problema mencionado anteriormente, pero al no saber utilizar y no haberlo dado (y por lo tanto, hacer uso de IA generativa), he preferido no utilizarlo.

In [ ]:
#Ejemplo del error que aparece al introducir un símbolo que no pertenece a las operaciones permitidas (M en este caso):
'''---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[33], line 80
     75     print("Resultado:")
     76     print(resultado)
---> 80 main()

Cell In[33], line 73, in main()
     70 print()
     71 print(f"*** Ejecutando operación: {signo} ***")
---> 73 resultado = array_calculator(a, b, signo)
     74 print()
     75 print("Resultado:")

Cell In[33], line 48, in array_calculator(array1, array2, operation)
     45     return transponer(array1)
     46 else:
     47     # Este es el error exacto que pide el PDF
---> 48     raise ValueError(f"Operation '{operation}' not supported")

ValueError: Operation 'M' not supported'''

# SOLUTION:

In [1]:
import numpy as np

#Como nos pide "helper functions", he supuesto que se refeire a funciones para cada operacion, con errores de cada operacion
def suma(a, b):
    if a.shape != b.shape:
        raise ValueError(f"Incompatible shapes for addition: {a.shape} and {b.shape}") #El error de la suma
    return a + b #Devuelve la suma

def resta(a, b):
    if a.shape != b.shape:
        raise ValueError(f"Incompatible shapes for subtraction: {a.shape} and {b.shape}") #El error de la resta
    return a - b #Devuelve la resta

def multiplicacion_matricial(a, b):
    if a.shape[1] != b.shape[0]:
        raise ValueError(f"Incompatible shapes for matrix multiplication: {a.shape} and {b.shape}") #El error de la multiplicacion
    return a @ b #Devuelve la multiplicacion matricial

def concatenacion(a, b): 
    if a.shape[1] != b.shape[1]:#He supuesto que la concatenacion es con columnas iguales (habrán mas filas), ya que no se especifica en el PDF
        raise ValueError("Arrays must have the same number of columns to concatenate on axis 0") #El error de la concatenacion
    return np.concatenate((a, b), axis=0) #Devuelve la concatenacion de a y b

def transponer(a): #Una traspuesta no tiene error
    return a.T


def array_calculator(array1: np.ndarray, array2: np.ndarray, operation: str) -> np.ndarray:
    # Las operaciones de la calculadora hacia funciones de cada operacion
    if operation == '+':
        return suma(array1, array2)
    elif operation == '-':
        return resta(array1, array2)
    elif operation == '*':
        return multiplicacion_matricial(array1, array2)
    elif operation == 'concat':
        return concatenacion(array1, array2)
    elif operation == 'transpose':
        return transponer(array1)
    else:
        # Este es el error exacto que pide el PDF
        raise ValueError(f"Operation '{operation}' not supported")


def main():
    print("Accediendo a la calculadora de NumPy...")
    a = np.array([[0,1,2], #Nuestra matriz A, MODIFICABLE
                [3,4,5],
                [6,7,8]])
    print("Array A:")
    print(a)
    print()

    b = np.array([[0,1,2], #Nuestra matriz B, MODIFICABLE
                [3,4,5],
                [6,7,8]])
    print("Array B:")
    print(b)
    #lista_operaciones = ['+', '-', '*', 'concat', 'transpose'], para saber que operaciones se pueden hacer.

    signo = '*' #Nuestro signo (operacion que vamos a realizar), MODIFICABLE

    print()
    print(f"*** Ejecutando operación: {signo} ***")
    
    resultado = array_calculator(a, b, signo)
    print()
    print("Resultado:")
    print(resultado)

main()

Accediendo a la calculadora de NumPy...
Array A:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Array B:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

*** Ejecutando operación: * ***

Resultado:
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
