# 5.5.3. Exercise 3

You have to solve the following problems using numpy:

- Create a 10x10 matrix with your own seed. Make sure that the values are 0 or 1. Also make sure that the diagonal is 0, so you don’t have loops in your graph.

- Calculate the degree matrix of the graph. Formula: 

- Calculate the Laplacian matrix of the graph. Formula: 

- Calculate the normalized Laplacian matrix of the graph.
- Create a function that given an adjacency matrix and value, returns the number of nodes that have same or more degree than the value. The function must receive as input the adjacency matrix and the value. The function must return a numpy array with the number of nodes that have same or more degree than the value.

In [50]:
import numpy as np
'''PARA EL APARTADO A:'''
np.random.seed(42)

#En este primer paso, creamos una matriz 10x10 que tenga ceros o unos
A = np.random.randint(0, 2, (10, 10))
#Ahora, pasamos por cada elemento [i, i], y sustituimos por cero
for i in range(len(A)):
        A[i,i] = 0
#finalmente,imprimimos la A
print("a)\n",A)

'''PARA EL APARTADO B:'''
#Primero, debemos sumar todas las filas:
grados = np.sum(A, axis=1) #Este es el número de unos que hay en la fila
#Ahora, queremos poner ese número en la diagonal (pero en una matriz nula):
#Creamos la matriz nula:
D = np.random.randint(0, 1, (10, 10))
#Bucle para rellenar la diagnoal con los valores de los grados
for i in range(len(A)):
    D[i, i] = grados[i]
#Imprimimos la matriz:
print("b)\n",D)


'''PARA EL APARTADO C:'''
# La matriz de Laplace nos dice que tenemos que restar el apartado b - apartado a:
L = D-A
#Imprimimos la matriz L:
print("c)\n",L)

'''PARA EL APARTADO D:'''
#La matriz de Laplace normalizada es D**(-1/2) * L * D**(-1/2)
#Primero, calcular D**(-1/2), como con 0 da problemas, cogemos la diagonal y operamos con ella:
#Creamos una matriz nula para insertar los valores operados del array grados

Dprima = np.zeros((10,10), dtype=float) #Linea de codigo generada con IA (tuve que buscar cómo poner una matriz como float para evitar que hubisese fallos en el programa)

for i in range(len(grados)):
    Dprima[i, i] = 1/ np.sqrt(grados[i]) #Calcula el **(-1/2)

#Ahora, ya podemos calcular la matirz de laplace normalizada:
Lnorm = Dprima @ L @ Dprima
print("d)\n",Lnorm)

'''PARA EL APARTADO E:'''
#Nos dicen que creemos una funcion:
def nnodosmayorgrado(adjunta, valor):
     #Como hemos hecho en un apartado anterior, sumamos los valores de la fila de la matriz adjunta:
     suma_filas= np.sum(adjunta, axis = 1)
     #print(suma_filas), solo para comprobar
     #Ahora, debemos ver si la suma de la fila es mayor que el valor introducido:
     mayoresquevalor = np.sum(suma_filas >= valor)
     return mayoresquevalor
matriz = A
valor = 4
resultadoe = nnodosmayorgrado(matriz, valor)
print("e)\n",resultadoe, "son las filas cuya suma valen mas que el valor introducido")

a)
 [[0 1 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 1 1 0]
 [1 0 0 1 1 1 1 1 1 1]
 [0 0 1 0 1 0 1 0 0 0]
 [0 0 1 1 0 1 1 0 1 1]
 [0 1 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 1 1]
 [1 1 0 1 0 1 1 0 0 1]
 [0 1 0 1 0 0 1 0 0 1]
 [1 1 1 1 1 1 1 1 1 0]]
b)
 [[3 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 8 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 6 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 9]]
c)
 [[ 3 -1  0  0  0 -1  0  0  0 -1]
 [ 0  4  0  0 -1  0 -1 -1 -1  0]
 [-1  0  8 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0 -1  3 -1  0 -1  0  0  0]
 [ 0  0 -1 -1  6 -1 -1  0 -1 -1]
 [ 0 -1  0 -1  0  3 -1  0  0  0]
 [ 0  0  0  0  0 -1  3  0 -1 -1]
 [-1 -1  0 -1  0 -1 -1  6  0 -1]
 [ 0 -1  0 -1  0  0 -1  0  4 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  9]]
d)
 [[ 1.         -0.28867513  0.          0.          0.         -0.33333333
   0.          0.          0.         -0.19245009]
 [ 0.          1.          0.          0.         -0.20412415  0.
